version: 2
jobs:
  build:
    docker:
      - image: node:16
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-cache-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "elm.json" }}
      - run:
          name: Install sysconfcpus to fix core count detection
          command: |
            git clone https://github.com/obmarg/libsysconfcpus.git;
            cd libsysconfcpus;
            ./configure;
            make && make install;
            cd ..;
      - run:
          name: Install elm
          command: >
            mkdir ~/.npm-global
            && npm config set prefix '~/.npm-global'
            && npm install --unsafe-perm -g elm@0.19.0-bugfix6
      - run:
          name: Install dependencies
          command: sysconfcpus -n 2 make setup
      - run:
          name: Build project
          command: sysconfcpus -n 2 make dist
      - run:
          name: Test project
          command: sysconfcpus -n 2 make test
      - run:
          name: Validate formatting
          command: sysconfcpus -n 2 npx elm-format --validate src/
      - save_cache:
          key:  v4-cache-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "elm.json" }}
          paths:
            - elm-stuff
            - node_modules

